/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogosorte;

import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lavie
 */
public class AppJogo extends javax.swing.JFrame {

    /**
     * Creates new form AP
     */
    public AppJogo() {
        initComponents();
        jButtonOk.setEnabled(false);
        jButtonGirar.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
         jLabelValor.setText(""+dinheiro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonGirar = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fça a sua Aposta");
        setMinimumSize(new java.awt.Dimension(690, 580));

        jPanel1.setMaximumSize(new java.awt.Dimension(327, 327));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Angola.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 110, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Inglaterra.jpeg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 160, 80, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Espanha.jpeg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 25, 110, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Franca.jpeg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 150, 90, 90);

        jButtonGirar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGirar.setText("Girar");
        jButtonGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGirar);
        jButtonGirar.setBounds(120, 340, 180, 40);

        jButtonOk.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk);
        jButtonOk.setBounds(430, 340, 108, 40);

        buttonGroup1.add(jCheckBox1);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(150, 30, 110, 29);

        buttonGroup1.add(jCheckBox2);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(400, 40, 120, 23);

        buttonGroup1.add(jCheckBox3);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(170, 150, 90, 29);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(380, 170, 90, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma Aposta", "5 Euros", "10 Euros", "20 Euros", "50 Euros", "100 Euros" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(440, 110, 170, 35);

        jLabel10.setText("Aposta Aqui");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 80, 150, 20);

        jLabelValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelValor);
        jLabelValor.setBounds(460, 210, 140, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarActionPerformed

        new jogo().start();
        jButtonGirar.setEnabled(true);
        jButtonOk.setEnabled(true);
        
            jComboBox1.setEnabled(false);
            jCheckBox4.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox1.setSelected(false);
            jCheckBox3.setSelected(false);
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        
    }//GEN-LAST:event_jButtonGirarActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        int nr1 = r.nextInt(3)+1;
         int nr2 = r.nextInt(3)+1;
          int nr3 = r.nextInt(3)+1;
           int nr4 = r.nextInt(3)+1;
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
     
        if (jCheckBox4.isSelected() == true || jCheckBox2.isSelected() == true || jCheckBox1.isSelected() == true || jCheckBox3.isSelected() == true) {
           // System.out.println(""+nr);
          jCheckBox1.setText(""+nr1);
        jCheckBox2.setText(""+nr2);
        jCheckBox3.setText(""+nr3);
        jCheckBox4.setText(""+nr4);
            if (jCheckBox1.isSelected() == true &&nr1==1){
                if(aposta==5){
                     premio=500*5;
                     dinheiro=dinheiro+premio;
                      jCheckBox1.setText(""+nr1+"-> "+premio);
                      JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==10){
                     premio=500*10;
                     dinheiro=dinheiro+premio; 
                      jCheckBox1.setText(""+nr1+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==20){
                     premio=500*20;
                     dinheiro=dinheiro+premio; 
                      jCheckBox1.setText(""+nr1+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==50){
                     premio=500*10;
                     dinheiro=dinheiro+premio; 
                      jCheckBox1.setText(""+nr1+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==100){
                     premio=500*100;
                     dinheiro=dinheiro+premio; 
                      jCheckBox1.setText(""+nr1+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                }
               
               
             
           }
           else  if (jCheckBox2.isSelected() == true &&nr2==1){
                if(aposta==5){
                     premio=500*5;
                     dinheiro=dinheiro+premio;
                      jCheckBox2.setText(""+nr2+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==10){
                     premio=500*10;
                     dinheiro=dinheiro+premio; 
                      jCheckBox2.setText(""+nr2+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==20){
                     premio=500*20;
                     dinheiro=dinheiro+premio; 
                      jCheckBox2.setText(""+nr2+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==50){
                     premio=500*10;
                     dinheiro=dinheiro+premio;
                      jCheckBox2.setText(""+nr2+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==100){
                     premio=500*100;
                     dinheiro=dinheiro+premio; 
                      jCheckBox2.setText(""+nr2+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                }
               
             
           }   else  if (jCheckBox3.isSelected() == true &&nr3==1){
                if(aposta==5){
                     premio=500*5;
                     dinheiro=dinheiro+premio;
                      jCheckBox3.setText(""+nr3+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==10){
                     premio=500*10;
                     dinheiro=dinheiro+premio; 
                      jCheckBox3.setText(""+nr3+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==20){
                     premio=500*20;
                     dinheiro=dinheiro+premio; 
                      jCheckBox3.setText(""+nr3+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==50){
                     premio=500*10;
                     dinheiro=dinheiro+premio;
                      jCheckBox3.setText(""+nr3+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==100){
                     premio=500*100;
                     dinheiro=dinheiro+premio; 
                      jCheckBox3.setText(""+nr3+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                }
               
             
           }  else  if (jCheckBox4.isSelected() == true &&nr4==1){
                if(aposta==5){
                     premio=500*5;
                     dinheiro=dinheiro+premio;
                      jCheckBox4.setText(""+nr4+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==10){
                     premio=500*10;
                     dinheiro=dinheiro+premio; 
                      jCheckBox4.setText(""+nr4+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==20){
                     premio=500*20;
                     dinheiro=dinheiro+premio; 
                      jCheckBox4.setText(""+nr4+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==50){
                     premio=500*10;
                     dinheiro=dinheiro+premio;
                      jCheckBox4.setText(""+nr4+"-> "+premio);
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                } else if(aposta==100){
                     premio=500*100;
                     dinheiro=dinheiro+premio; 
                      jCheckBox4.setText(""+nr4+"-> "+premio);
                      
             JOptionPane.showMessageDialog(this, "Ganhaste "+premio);
                }
               
             
           }else{
               JOptionPane.showMessageDialog(this, "Perdeu ");
               if(aposta==5){
                     dinheiro=dinheiro-5;
               }else if(aposta==10){
                     dinheiro=dinheiro-10;
               } else if(aposta==20){
                     dinheiro=dinheiro-20;
               } else if(aposta==50){
                     dinheiro=dinheiro-50;
               }else if(aposta==100){
                     dinheiro=dinheiro-100;
               }
               
           }
           
            jLabelValor.setText(""+dinheiro);
            jButtonGirar.setEnabled(false);
            jButtonOk.setEnabled(false);
            jComboBox1.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "Esecolhe Uma Opção!");
        }
           
         
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int opcao = jComboBox1.getSelectedIndex();
        if (opcao>0){
            jButtonGirar.setEnabled(true);
            if(opcao==1){
                 aposta = 5;
                 
            }
            else if(opcao==2){
               aposta = 10;  
            }
       else if(opcao==3){
            aposta = 20;
       } else if(opcao==4){
            aposta = 50;
       } else if(opcao==5){
            aposta = 100;
       }
      
        }
         
        else{
        JOptionPane.showMessageDialog(this, "opcao");
          jButtonGirar.setEnabled(false);
    }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    
    // para permitir gerar
    private class jogo extends Thread {

        public void run() {
            for (int i = 0; i < 10; i++) {
                try {
                   
                    int nr1 = r.nextInt(6) + 1;
                    int nr2 = r.nextInt(6) + 1;
                    int nr3 = r.nextInt(6) + 1;
                    int nr4 = r.nextInt(6) + 1;

                    jLabel1.setIcon(imagem[nr1]);
                    jLabel2.setIcon(imagem[nr2]);
                    jLabel3.setIcon(imagem[nr3]);
                    jLabel4.setIcon(imagem[nr4]);
                    Thread.sleep(100);

                } catch (InterruptedException ex) {
                    Logger.getLogger(AppJogos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppJogo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonGirar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 ImageIcon imagem[] = {new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Angola.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Espanha.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Franca.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/senegal.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/Inglaterra.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/cabo-verde.jpeg")),
        new javax.swing.ImageIcon(getClass().getResource("/BandeirasPaises/portugal.jpeg"))
    };
 Random r = new Random();
 double dinheiro=1000, premio;
 
 int aposta=5;
}
